### ISSUE TITLE
Redirect Loop with Ory Network (CSRF Violation)

### ISSUE THREAD

**Issue by gwoodbridge** [karlis-vagalis/kratos-selfservice#1]
I am experiencing a redirect loop issue on Cloudflare Pages after integrating with Ory Network. The environment variable is correctly set to my Ory Network project's URL. Access attempts to any page result in a cycle between my login page (cloudflare-slug.pages.dev/login) and Ory's self-service login (ory-slug.projects.oryapis.com/self-service/login/browser), which successfully returns a login URL with a flowID but ultimately loops back to the login page. I've narrowed this down to the redirect for a csrf violation. Are there any other settings I need to change besides the custom UI URL to keep from getting this csrf violation?

**Comment by karlis-vagalis** [comment]
Thanks for submitting the issue.

Short answer: no, there are no other explicit variables.

I am not aware yet, as I have used only self hosted Kratos thus far, but I will try to reproduce the error.

**Comment by karlis-vagalis** [comment]
Are you using dockerized version? Or how did you deploy the UI to Cloudflare Pages? I thought Cloudflare Pages only support static websites, which theoretically this UI is, but unfortunately it can not be built using `adapter-static` due to dynamic URL parameters like flowID.

**Comment by gwoodbridge** [comment]
Cloudflare Pages has their own adapter and supports dynamic content by generating Cloudflare functions. To get it up and running I just changed the adapter, pushed it to my Github repo, and pointed Cloudflare there. I also update the Ory Network Custom UI URLs to the Cloudflare pages URL. I run into the same redirect issue when I initiate Ory Proxy and run everything on localhost as well. I guess to try and debug, I can work on self-hosting a Kratos instance.

**Comment by karlis-vagalis** [comment]
I think your assessment of the cause of the issue is correct. The issue is, that the anti-csrf cookie cannot be set by the browser, because the Ory's self-service domain (ory-slug.projects.oryapis.com) is different from your UI's domain (cloudflare-slug.pages.dev/login).

Therefore inside of Ory Console you have to add custom domain (cloudflare-slug.pages.dev), so that cookie can be set correctly. Afterwards, the issue should disappear. Unfortunately I am not particularly familiar with Ory Proxy/Tunnel, which if I understand correctly, should help avoid this issue. Indeed, for the development and production purposes I have used, I have relied on self-hosted Kratos instance and defined `base_url`and/or cookie domain setting same as my development machine.

**Comment by gwoodbridge** [comment]
I've successfully deployed the self-hosted version, resolving my initial issues. I misunderstood the domain setting for cookies, thinking it was tied to the custom UI URL instead of Ory's self-service domain. I'm not sure why the Tunnel and Proxy didn't work, but I can now progress with development. It seems custom domain configuration for Ory Network access is not available on the developer tier, but I expect it to work in production once I upgrade to a paid plan. Thank you for the support and the great template!
